/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.BorderLayout;
import java.awt.Font;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tranh
 */
public class QuanLyCF extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyCF
     */
    private DefaultTableModel model;

    public QuanLyCF() {
        initComponents();

        setTitle("Trang Menu Chính");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Đóng Frame này khi nhấn X

        JPanel panel = new JPanel();
        JLabel label = new JLabel("<html><center>Chào mừng đến với<br>Trang Quản lý Menu</center></html>");
        label.setFont(new Font("Segoe UI", Font.BOLD, 24));
        panel.add(label);
        add(panel, BorderLayout.CENTER);

        // Nút "Quay lại" (tùy chọn)
        JButton btnQuayLai = new JButton("Quay lại Trang Chính");
        btnQuayLai.addActionListener(e -> {
            this.dispose(); // Đóng MenuFrame hiện tại
            new QuanLyCF().setVisible(true); // Tạo và hiển thị lại QuanLyCF
        });
        JPanel southPanel = new JPanel();
        southPanel.add(btnQuayLai);
        add(southPanel, BorderLayout.SOUTH);

        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbQLCF = new javax.swing.JLabel();
        lbMenu = new javax.swing.JLabel();
        pnCFMuoi = new javax.swing.JPanel();
        btnXemchitietBacXiu = new javax.swing.JButton();
        lbBxiu = new javax.swing.JLabel();
        textCaPheMuoi = new javax.swing.JLabel();
        pnBxiu = new javax.swing.JPanel();
        btnXemchitietBacXiu1 = new javax.swing.JButton();
        lbBxiu1 = new javax.swing.JLabel();
        textBxiu = new javax.swing.JLabel();
        pnMatchaLatte = new javax.swing.JPanel();
        btnXemchitietBacXiu2 = new javax.swing.JButton();
        lbBxiu2 = new javax.swing.JLabel();
        textMatchaLatte = new javax.swing.JLabel();
        pnXoaiChanhLeo = new javax.swing.JPanel();
        btnXemchitietBacXiu3 = new javax.swing.JButton();
        lbBxiu3 = new javax.swing.JLabel();
        textXoaiChanhLeo = new javax.swing.JLabel();
        pnMatchaDaXay = new javax.swing.JPanel();
        btnXemchitietBacXiu4 = new javax.swing.JButton();
        lbBxiu4 = new javax.swing.JLabel();
        textMatcha_daxay = new javax.swing.JLabel();
        pnCFNau = new javax.swing.JPanel();
        btnXemchitietBacXiu6 = new javax.swing.JButton();
        lbBxiu6 = new javax.swing.JLabel();
        textCaPheNau = new javax.swing.JLabel();
        btnQLKH = new javax.swing.JButton();
        btnQLNL = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbQLCF.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbQLCF.setForeground(new java.awt.Color(255, 51, 153));
        lbQLCF.setText("Quản lý Cà Phê");

        lbMenu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbMenu.setForeground(new java.awt.Color(255, 0, 204));
        lbMenu.setText("MENU");

        pnCFMuoi.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnXemchitietBacXiu.setText("Xem chi tiết");
        btnXemchitietBacXiu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemchitietBacXiuActionPerformed(evt);
            }
        });

        lbBxiu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ca-phe-muoi.png"))); // NOI18N

        textCaPheMuoi.setText("Cà phê muối");

        javax.swing.GroupLayout pnCFMuoiLayout = new javax.swing.GroupLayout(pnCFMuoi);
        pnCFMuoi.setLayout(pnCFMuoiLayout);
        pnCFMuoiLayout.setHorizontalGroup(
            pnCFMuoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCFMuoiLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(pnCFMuoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbBxiu)
                    .addComponent(btnXemchitietBacXiu)
                    .addGroup(pnCFMuoiLayout.createSequentialGroup()
                        .addComponent(textCaPheMuoi)
                        .addGap(18, 18, 18)))
                .addGap(24, 24, 24))
        );
        pnCFMuoiLayout.setVerticalGroup(
            pnCFMuoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCFMuoiLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbBxiu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textCaPheMuoi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXemchitietBacXiu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnBxiu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnXemchitietBacXiu1.setText("Xem chi tiết");
        btnXemchitietBacXiu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemchitietBacXiu1ActionPerformed(evt);
            }
        });

        lbBxiu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bac-xiu-da.png"))); // NOI18N

        textBxiu.setText("Bạc xỉu");

        javax.swing.GroupLayout pnBxiuLayout = new javax.swing.GroupLayout(pnBxiu);
        pnBxiu.setLayout(pnBxiuLayout);
        pnBxiuLayout.setHorizontalGroup(
            pnBxiuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBxiuLayout.createSequentialGroup()
                .addGroup(pnBxiuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnBxiuLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(textBxiu))
                    .addGroup(pnBxiuLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnXemchitietBacXiu1))
                    .addGroup(pnBxiuLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lbBxiu1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnBxiuLayout.setVerticalGroup(
            pnBxiuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBxiuLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lbBxiu1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textBxiu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXemchitietBacXiu1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pnMatchaLatte.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnXemchitietBacXiu2.setText("Xem chi tiết");
        btnXemchitietBacXiu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemchitietBacXiu2ActionPerformed(evt);
            }
        });

        lbBxiu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Matcha-latte.jpg"))); // NOI18N

        textMatchaLatte.setText("Matcha Latte");

        javax.swing.GroupLayout pnMatchaLatteLayout = new javax.swing.GroupLayout(pnMatchaLatte);
        pnMatchaLatte.setLayout(pnMatchaLatteLayout);
        pnMatchaLatteLayout.setHorizontalGroup(
            pnMatchaLatteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMatchaLatteLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(textMatchaLatte)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMatchaLatteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnMatchaLatteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnXemchitietBacXiu2)
                    .addComponent(lbBxiu2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69))
        );
        pnMatchaLatteLayout.setVerticalGroup(
            pnMatchaLatteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMatchaLatteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbBxiu2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textMatchaLatte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXemchitietBacXiu2)
                .addGap(12, 12, 12))
        );

        pnXoaiChanhLeo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnXemchitietBacXiu3.setText("Xem chi tiết");
        btnXemchitietBacXiu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemchitietBacXiu3ActionPerformed(evt);
            }
        });

        lbBxiu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tra-xoai-chanh-leo.png"))); // NOI18N

        textXoaiChanhLeo.setText("Trà Xoài Chanh Leo");

        javax.swing.GroupLayout pnXoaiChanhLeoLayout = new javax.swing.GroupLayout(pnXoaiChanhLeo);
        pnXoaiChanhLeo.setLayout(pnXoaiChanhLeoLayout);
        pnXoaiChanhLeoLayout.setHorizontalGroup(
            pnXoaiChanhLeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnXoaiChanhLeoLayout.createSequentialGroup()
                .addGroup(pnXoaiChanhLeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnXoaiChanhLeoLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(pnXoaiChanhLeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnXemchitietBacXiu3)
                            .addComponent(textXoaiChanhLeo)))
                    .addGroup(pnXoaiChanhLeoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbBxiu3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pnXoaiChanhLeoLayout.setVerticalGroup(
            pnXoaiChanhLeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnXoaiChanhLeoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbBxiu3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(textXoaiChanhLeo)
                .addGap(12, 12, 12)
                .addComponent(btnXemchitietBacXiu3)
                .addContainerGap())
        );

        pnMatchaDaXay.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnXemchitietBacXiu4.setText("Xem chi tiết");
        btnXemchitietBacXiu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemchitietBacXiu4ActionPerformed(evt);
            }
        });

        lbBxiu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Matcha-da-xay.png"))); // NOI18N

        textMatcha_daxay.setText("Matcha đá xay");

        javax.swing.GroupLayout pnMatchaDaXayLayout = new javax.swing.GroupLayout(pnMatchaDaXay);
        pnMatchaDaXay.setLayout(pnMatchaDaXayLayout);
        pnMatchaDaXayLayout.setHorizontalGroup(
            pnMatchaDaXayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMatchaDaXayLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnMatchaDaXayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXemchitietBacXiu4)
                    .addGroup(pnMatchaDaXayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbBxiu4, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(textMatcha_daxay, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        pnMatchaDaXayLayout.setVerticalGroup(
            pnMatchaDaXayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMatchaDaXayLayout.createSequentialGroup()
                .addComponent(lbBxiu4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textMatcha_daxay)
                .addGap(18, 18, 18)
                .addComponent(btnXemchitietBacXiu4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnCFNau.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnXemchitietBacXiu6.setText("Xem chi tiết");
        btnXemchitietBacXiu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemchitietBacXiu6ActionPerformed(evt);
            }
        });

        lbBxiu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ca-phe-sua.png"))); // NOI18N

        textCaPheNau.setText("Cà phê nâu");

        javax.swing.GroupLayout pnCFNauLayout = new javax.swing.GroupLayout(pnCFNau);
        pnCFNau.setLayout(pnCFNauLayout);
        pnCFNauLayout.setHorizontalGroup(
            pnCFNauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCFNauLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbBxiu6)
                .addGap(0, 17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCFNauLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textCaPheNau)
                .addGap(39, 39, 39))
            .addGroup(pnCFNauLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnXemchitietBacXiu6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnCFNauLayout.setVerticalGroup(
            pnCFNauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCFNauLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbBxiu6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textCaPheNau)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXemchitietBacXiu6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnQLKH.setText("QLKH");
        btnQLKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLKHActionPerformed(evt);
            }
        });

        btnQLNL.setText("QL Nguyên Liệu");
        btnQLNL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLNLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnMatchaLatte, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(pnBxiu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnCFNau, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnMatchaDaXay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnXoaiChanhLeo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pnCFMuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnQLNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnQLKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(lbMenu))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(lbQLCF)))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lbQLCF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbMenu)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnCFMuoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnCFNau, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnBxiu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(btnQLKH)
                        .addGap(42, 42, 42)
                        .addComponent(btnQLNL)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnMatchaDaXay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnMatchaLatte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnXoaiChanhLeo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXemchitietBacXiuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemchitietBacXiuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXemchitietBacXiuActionPerformed

    private void btnXemchitietBacXiu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemchitietBacXiu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXemchitietBacXiu1ActionPerformed

    private void btnXemchitietBacXiu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemchitietBacXiu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXemchitietBacXiu2ActionPerformed

    private void btnXemchitietBacXiu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemchitietBacXiu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXemchitietBacXiu3ActionPerformed

    private void btnXemchitietBacXiu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemchitietBacXiu4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXemchitietBacXiu4ActionPerformed

    private void btnXemchitietBacXiu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemchitietBacXiu6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXemchitietBacXiu6ActionPerformed

    private void btnQLKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLKHActionPerformed
        // TODO add your handling code here:
        new QLKH().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQLKHActionPerformed

    private void btnQLNLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLNLActionPerformed
        // TODO add your handling code here:
        new QuanLyNguyenLieu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQLNLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyCF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyCF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyCF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyCF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyCF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQLKH;
    private javax.swing.JButton btnQLNL;
    private javax.swing.JButton btnXemchitietBacXiu;
    private javax.swing.JButton btnXemchitietBacXiu1;
    private javax.swing.JButton btnXemchitietBacXiu2;
    private javax.swing.JButton btnXemchitietBacXiu3;
    private javax.swing.JButton btnXemchitietBacXiu4;
    private javax.swing.JButton btnXemchitietBacXiu6;
    private javax.swing.JLabel lbBxiu;
    private javax.swing.JLabel lbBxiu1;
    private javax.swing.JLabel lbBxiu2;
    private javax.swing.JLabel lbBxiu3;
    private javax.swing.JLabel lbBxiu4;
    private javax.swing.JLabel lbBxiu6;
    private javax.swing.JLabel lbMenu;
    private javax.swing.JLabel lbQLCF;
    private javax.swing.JPanel pnBxiu;
    private javax.swing.JPanel pnCFMuoi;
    private javax.swing.JPanel pnCFNau;
    private javax.swing.JPanel pnMatchaDaXay;
    private javax.swing.JPanel pnMatchaLatte;
    private javax.swing.JPanel pnXoaiChanhLeo;
    private javax.swing.JLabel textBxiu;
    private javax.swing.JLabel textCaPheMuoi;
    private javax.swing.JLabel textCaPheNau;
    private javax.swing.JLabel textMatchaLatte;
    private javax.swing.JLabel textMatcha_daxay;
    private javax.swing.JLabel textXoaiChanhLeo;
    // End of variables declaration//GEN-END:variables
}
