/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author ADMIN
 */
public class TrangChuNV extends javax.swing.JFrame {
    private JPanel mainPanel;
    private CardLayout cardLayout;
    /**
     * Creates new form TrangchuNV
     */
    public TrangChuNV() {
        setTitle("Trang chủ quản lý");
        setSize(800, 600);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setLayout(null);

        // Các nút menu
        JButton btnQLKH = new JButton("Quản lý khách hàng");
        btnQLKH.setBounds(20, 20, 180, 30);
        add(btnQLKH);

        JButton btnQLNL = new JButton("Quản lý nguyên liệu");
        btnQLNL.setBounds(20, 60, 180, 30);
        add(btnQLNL);

        JButton btnQLBan = new JButton("Quản lý bàn");
        btnQLBan.setBounds(20, 100, 180, 30);
        add(btnQLBan);

        JButton btnThongKe = new JButton("Thống kê doanh thu");
        btnThongKe.setBounds(20, 140, 180, 30);
        add(btnThongKe);

        // Panel chính dùng CardLayout
        cardLayout = new CardLayout();
        mainPanel = new JPanel(cardLayout);
        mainPanel.setBounds(220, 20, 540, 520);
        add(mainPanel);

        // Thêm các panel chức năng vào mainPanel
        JPanel panelQLKH = new QLKHPanel(); // JPanel quản lý khách hàng
        JPanel panelQLNL = new QLNLPanel(); // JPanel quản lý nguyên liệu
        JPanel panelQLBan = new QLBanPanel(); // JPanel quản lý bàn
        JPanel panelThongKe = new ThongKePanel(); // JPanel thống kê doanh thu

        mainPanel.add(panelQLKH, "QLKH");
        mainPanel.add(panelQLNL, "QLNL");
        mainPanel.add(panelQLBan, "QLBan");
        mainPanel.add(panelThongKe, "ThongKe");

        // Sự kiện chuyển panel
        btnQLKH.addActionListener(e -> cardLayout.show(mainPanel, "QLKH"));
        btnQLNL.addActionListener(e -> cardLayout.show(mainPanel, "QLNL"));
        btnQLBan.addActionListener(e -> cardLayout.show(mainPanel, "QLBan"));
        btnThongKe.addActionListener(e -> cardLayout.show(mainPanel, "ThongKe"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChuNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChuNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChuNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChuNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChuNV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
